development:
  :address: "mail.sciencify.com"
  :port: 25
  :authentication: "plain"
  :user_name: "team@sciencify.com"
  #:password: <%= ENV['SMTP_PASSWORD'] %>
  :enable_starttls_auto: false
production:
  :address: "mail.sciencify.com"
  :port: 25
  :authentication: "plain"
  :user_name: "team@sciencify.com"
  #:password: <%= ENV['SMTP_PASSWORD'] %> TODO: Make this work
  :enable_starttls_auto: false
